<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
   	<DefineConstants>Release</DefineConstants>
  </PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Syncfusion.Blazor.Buttons" Version="34.1.29" />
		<PackageReference Include="Syncfusion.Blazor.Charts" Version="34.1.29" />
		<PackageReference Include="Syncfusion.Blazor.Grid" Version="34.1.29" />
		<PackageReference Include="Syncfusion.Blazor.Navigations" Version="34.1.29" />
		<PackageReference Include="Syncfusion.Blazor.Notifications" Version="34.1.29" />
		<PackageReference Include="Syncfusion.Blazor.Schedule" Version="34.1.29" />
		<PackageReference Include="Syncfusion.Blazor.Themes" Version="34.1.29" />
	</ItemGroup>
</Project>
